(async()=>{const $=id=>document.getElementById(id),API='https://rps-server.heyboernathan.workers.dev';let token='',stats={};function draw(id,list){const root=$(id);root.replaceChildren();list.forEach(a=>{const card=document.createElement('article');card.className='badge'+(a.ok?'':' locked');const icon=document.createElement('div');icon.className='icon';icon.textContent=a.icon;const body=document.createElement('div');body.style.flex='1';const title=document.createElement('strong');title.textContent=(a.ok?'✓ ':'🔒 ')+a.name;const desc=document.createElement('small');desc.textContent=a.desc;const progress=document.createElement('div');progress.className='progress';const fill=document.createElement('span');fill.style.width=Math.min(100,Math.round(a.val/a.goal*100))+'%';progress.append(fill);body.append(title,desc,progress);card.append(icon,body);root.append(card)})}async function request(action,extra={}){if(!token)throw Error('Log in to load your saved achievements.');const r=await fetch(API+'/account/arcade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action,...extra}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Could not load saved achievements.');return d}try{token=localStorage.getItem('token')||'';const d=await request('load');stats=d.data?.stats||{};const games=stats.games||0,wins=stats.wins||0,losses=stats.losses||0,ties=stats.ties||0,best=stats.bestStreak||0,pct=games?Math.round(wins/games*100):0;$('games').textContent=games;$('winrate').textContent=pct+'%';$('best').textContent=best;$('ratio').textContent=wins;const freeMilestones=[
['🌱','First Steps','Play your first arcade round.',1,games],['✊','Triple Threat','Play 10 rounds.',10,games],['🔥','Hot Hand','Build a 3-win streak.',3,best],['🏆','Rising Champion','Win 25 rounds.',25,wins],['🧱','Never Give Up','Play 50 rounds.',50,games],['🎯','Clean Sweep','Win 10 rounds.',10,wins],['🧭','Getting Started','Play 5 rounds.',5,games],['🌟','First Five','Win 5 rounds.',5,wins],['⚖️','Even Keel','Play 10 rounds.',10,games],['🪨','Rock Solid','Win 15 rounds.',15,wins],['📄','Paper Trail','Play 25 rounds.',25,games],['✂️','Sharp Moves','Reach a 5-win streak.',5,best],['🎲','Tie Breaker','Finish 3 tied rounds.',3,ties],['🛡️','Comeback Kid','Win 20 rounds.',20,wins],['🚀','On a Roll','Reach a 7-win streak.',7,best],['🥉','Bronze Grinder','Play 75 rounds.',75,games],['🥈','Silver Grinder','Win 40 rounds.',40,wins],['🌈','Variety Player','Play 100 rounds.',100,games],['🏅','Streak Starter','Reach a 4-win streak.',4,best],['👑','Free Legend','Win 50 rounds.',50,wins]];
const all=freeMilestones.map(([icon,name,desc,goal,val])=>({icon,name,desc,goal,val,ok:val>=goal}));draw('free-badges',all);$('unlock').addEventListener('click',async()=>{try{const r=await fetch(API+'/account/premium',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token}),cache:'no-store'});const p=await r.json().catch(()=>({}));if(!r.ok||p.premium!==true)throw Error('Advanced analytics are Premium-only.');$('premium-msg').textContent='Premium verified — advanced stats unlocked.';$('premium-panel').classList.remove('hidden');const sources=[
{key:'games',value:games,icon:'🎮',label:'Arcade Veteran',unit:'rounds',goals:[100,125,150,175,200,250,300,350,400,450,500,600,700,800,900,1000,1250,1500,1750,2000,2500,3000,4000,5000,7500]},
{key:'wins',value:wins,icon:'🏆',label:'Victory Collector',unit:'wins',goals:[100,125,150,175,200,250,300,350,400,450,500,600,700,800,900,1000,1250,1500,1750,2000,2500,3000,4000,5000,7500]},
{key:'best',value:best,icon:'🔥',label:'Streak Master',unit:'win streak',goals:[10,12,14,16,18,20,22,24,26,28,30,35,40,45,50,55,60,65,70,75,80,90,100,125,150]},
{key:'ties',value:ties,icon:'🤝',label:'Tie Specialist',unit:'ties',goals:[10,15,20,25,30,40,50,60,70,80,90,100,125,150,175,200,250,300,350,400,450,500,600,750,1000]},
{key:'losses',value:losses,icon:'🧠',label:'Resilient Rival',unit:'losses learned from',goals:[25,50,75,100,125,150,175,200,250,300,350,400,450,500,600,700,800,900,1000,1250,1500,1750,2000,2500,3000]}
];
const premium=sources.flatMap(source=>source.goals.map((goal,index)=>({icon:source.icon,name:source.label+' '+(index+1),desc:'Reach '+goal+' '+source.unit+'.',ok:source.value>=goal,goal,val:source.value}))).slice(0,100);
$('premium-count').textContent=premium.filter(a=>a.ok).length+' / 100 Premium milestones earned. Keep playing to unlock them all.';draw('premium-badges',premium);$('report').textContent=games<5?'Play at least five rounds to build your playstyle report.':(pct>=60?'You are winning often. Try higher difficulty modes to keep improving.':pct>=40?'Your results are balanced. Look for patterns in your last few choices.':'You are still learning. Mix up your choices and keep practicing.')+' Record: '+wins+' wins, '+losses+' losses, '+ties+' ties ('+pct+'% win rate).'}catch(e){$('premium-msg').textContent=e.message}})}catch(e){$('games').textContent='—';$('winrate').textContent='—';$('best').textContent='—';$('ratio').textContent='—';$('premium-msg').textContent=e.message;document.querySelectorAll('[data-premium-challenge]').forEach(b=>b.disabled=true)}})();