(() => {
const $=id=>document.getElementById(id), API='https://rps-server.heyboernathan.workers.dev', MOVES=['rock','paper','scissors'], ICON={rock:'✊',paper:'✋',scissors:'✌️'}, BEATS={rock:'scissors',paper:'rock',scissors:'paper'}, COUNTER={rock:'paper',paper:'scissors',scissors:'rock'};
const MODES={classic:{title:'Classic Streak',desc:'Keep playing to build your best win streak.',free:true,target:0,ai:'Arcade Bot'},chaos:{title:'Chaos Arena',desc:'The arena is wild. A random twist changes the rules every round.',premium:true,target:0,ai:'Chaos Bot'},sudden:{title:'Sudden Death+',desc:'A loss ends your run. How many wins can you chain together?',premium:true,target:0,ai:'Sudden Bot'},blind:{title:'Blind Pick',desc:'Choose A, B, or C. The moves are revealed after both choices.',premium:true,target:0,ai:'Mystery Bot'},long:{title:'Best of 15',desc:'First to eight round wins takes the series.',premium:true,target:8,ai:'Marathon Bot'},rival:{title:'Rival AI',desc:'This rival learns from your recent choices. Try not to become predictable.',premium:true,target:0,ai:'Rival AI'},boss:{title:'Boss Rush',desc:'Beat five boss rounds. Each boss has its own favorite move.',premium:true,target:5,ai:'Boss 1'}};
const params=new URLSearchParams(location.search),mode=params.get('mode')||'classic',cfg=MODES[mode]||MODES.classic;
let premium=false,stats={},history=[],series={w:0,l:0,t:0},run=0,boss=0,finished=false,lastRound=null,blindMap=[];
const getToken=()=>{try{return localStorage.getItem('token')}catch(e){return null}};
function loadStats(){try{stats=JSON.parse(localStorage.getItem('rpsArcadeStats')||'{}')}catch(e){stats={}};stats.games=stats.games||0;stats.wins=stats.wins||0;stats.losses=stats.losses||0;stats.ties=stats.ties||0;stats.streak=stats.streak||0;stats.bestStreak=stats.bestStreak||0}
function save(){try{localStorage.setItem('rpsArcadeStats',JSON.stringify(stats))}catch(e){}}
async function checkPremium(){if(!cfg.premium)return true;const t=getToken();if(!t)throw Error('Log in with a Premium account to play this mode.');const r=await fetch(API+'/account/premium',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:t}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.premium!==true)throw Error('This arcade mode is Premium-only.');return true}
function setText(id,text){$(id).textContent=text}
function update(){setText('wins',series.w);setText('losses',series.l);setText('streak',run);setText('series',mode==='long'?'Series: first to 8 wins.':mode==='boss'?'Bosses defeated: '+boss+'/5.':mode==='sudden'?'Current run: '+run+' wins.':'Best all-time streak: '+stats.bestStreak+'.')}
function symbol(move){return ICON[move]||'❔'}
function aiMove(){if(mode==='rival'&&history.length>=2){const last=history[history.length-1];const after=history.slice(0,-1).filter((m,i,a)=>i>0&&a[i-1]===history[history.length-2]);if(after.length){const predicted=after[Math.floor(Math.random()*after.length)];return COUNTER[predicted]||MOVES[Math.floor(Math.random()*3)]}}if(mode==='boss'){const fav=['rock','paper','scissors','rock','scissors'][boss];return Math.random()<.72?fav:MOVES[Math.floor(Math.random()*3)]}if(mode==='chaos'){return MOVES[Math.floor(Math.random()*3)]}if(mode==='rival'&&history.length){return Math.random()<.65?COUNTER[history[history.length-1]]:MOVES[Math.floor(Math.random()*3)]}return MOVES[Math.floor(Math.random()*3)]}
function start(){setText('mode-tag',cfg.premium?'PREMIUM ARCADE MODE':'FREE ARCADE MODE');setText('mode-title',cfg.title);setText('mode-desc',cfg.desc);setText('ai-name',cfg.ai);if(mode==='blind'){const bs=[...document.querySelectorAll('[data-move]')];bs.forEach((b,i)=>{b.querySelector('.symbol').textContent=['🅰️','🅱️','©️'][i];b.lastElementChild.textContent=['Option A','Option B','Option C'][i]});}update()}
function pick(playerMove){if(finished)return;let actualPlayer=playerMove;if(mode==='blind'){actualPlayer=blindMap[playerMove];}const enemy=aiMove();let result=actualPlayer===enemy?'tie':BEATS[actualPlayer]===enemy?'win':'loss';if(mode==='chaos'&&Math.random()<.22){result=result==='win'?'loss':result==='loss'?'win':'tie';setText('result','CHAOS FLIP! The arena reversed the result!')}else setText('result',result==='win'?'✨ ROUND WON!':result==='loss'?'Oof — the bot takes this round.':'🤝 Tie round!');setText('you-symbol',symbol(actualPlayer));setText('ai-symbol',symbol(enemy));setText('you-move',actualPlayer.toUpperCase());setText('ai-move',enemy.toUpperCase());if(mode==='blind'){document.querySelectorAll('[data-move]').forEach((b,i)=>{b.querySelector('.symbol').textContent=symbol(blindMap[['rock','paper','scissors'][i]]);b.lastElementChild.textContent=blindMap[['rock','paper','scissors'][i]].toUpperCase()})}history.push(actualPlayer);history=history.slice(-20);stats.games++;if(result==='win'){series.w++;stats.wins++;run++;stats.streak=run;stats.bestStreak=Math.max(stats.bestStreak,run)}else if(result==='loss'){series.l++;stats.losses++;run=0;stats.streak=0}else{series.t++;stats.ties++}
if(mode==='sudden'&&result==='loss'){finished=true;setText('result','💥 RUN OVER! Your run ended at '+series.w+' wins.');}if(mode==='long'&&series.w>=8){finished=true;setText('result','🏆 SERIES WON! You won the best-of-15.')}else if(mode==='long'&&series.l>=8){finished=true;setText('result','Series lost — reset and challenge the rival again.')}if(mode==='boss'){if(result==='win'){boss++;setText('ai-name',boss<5?'Boss '+(boss+1):'Boss Rush Champion');if(boss>=5){finished=true;setText('result','👑 BOSS RUSH CLEARED! You beat all five bosses!')}}else if(result==='loss'){boss=0;setText('result','Boss defeated you. Boss Rush restarts at Boss 1.')}}save();update();$('next').classList.remove('hidden');document.querySelectorAll('[data-move]').forEach(b=>b.disabled=true);if(finished){$('next').textContent='Play again';$('next').classList.remove('hidden')}lastRound={actualPlayer,enemy,result};}
function next(){if(finished){series={w:0,l:0,t:0};run=0;boss=0;finished=false;history=[];setText('you-symbol','❔');setText('ai-symbol','🤖');setText('you-move','Choose a move');setText('ai-move','Ready?');$('next').textContent='Next round';setText('result','New run. Make your move!')}if(mode==='blind'){const shuffled=[...MOVES].sort(()=>Math.random()-.5);blindMap={rock:shuffled[0],paper:shuffled[1],scissors:shuffled[2]};document.querySelectorAll('[data-move]').forEach((b,i)=>{b.querySelector('.symbol').textContent=['🅰️','🅱️','©️'][i];b.lastElementChild.textContent=['Option A','Option B','Option C'][i];b.disabled=false;b.classList.remove('selected')})}else document.querySelectorAll('[data-move]').forEach(b=>b.disabled=false);$('next').classList.add('hidden');update()}
document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{if(mode==='blind')pick(b.dataset.move);else pick(b.dataset.move)}));$('next').addEventListener('click',next);
loadStats();start();checkPremium().then(()=>{premium=true;setText('gate-msg','Premium verified — have fun!')}).catch(e=>{if(cfg.premium){setText('gate-msg',e.message);document.querySelectorAll('[data-move]').forEach(b=>b.disabled=true);$('next').disabled=true;const div=document.createElement('a');div.href='/';div.className='action';div.style.display='block';div.style.textAlign='center';div.style.textDecoration='none';div.style.marginTop='10px';div.textContent='Back to main game / Premium';$('gate-msg').after(div)}});if(!cfg.premium)premium=true;
})();